Generic cavity model added.
frib-high-level-controls/FLAME pull request #19
Opened 2016-12-29 23:59 UTC by hezq06

Generic cavity model added. Test for generic cavity created and passed.

2017-01-06 15:37 UTC, mdavidsaver commented
@shengb As requested, I intend to take a look through this in the next day or so.

2017-01-09 16:20 UTC, mdavidsaver requested changes
There are a couple of changes I'd like to see.  Pass vector by const-ref and use consistent indentation.

There rest are points I'd like you to consider, but don't consider essential.

2017-01-09 16:20 UTC, mdavidsaver commented on src/flame/rf_cavity.h
> +    double calFitPow(double kfac, std::vector<double> Tfit) const;
Always pass non-primitive types by constant reference to avoid unnecessary copying.  That is ```const std::vector<double>& Tfit```.

2017-01-09 16:20 UTC, mdavidsaver commented on src/rf_cavity.cpp
> +double GetCavPhase(const int cavi, const Particle& ref, const double IonFys, const double multip , std::vector<double> P);
Another vector which should be passed as a constant reference.

2017-01-09 16:20 UTC, mdavidsaver commented on src/rf_cavity.cpp
> +double GetCavPhase(const int cavi, const Particle& ref, const double IonFys, const double multip, std::vector<double> P)
Another vector which should be passed as a constant reference.

2017-01-09 16:20 UTC, mdavidsaver commented on src/flame/rf_cavity.h
> +        std::vector<double> Tfit, Sfit;
It seems like these always have 10 elements?  If this is the case, it would be helpful to mention this in a comment here.

2017-01-09 16:20 UTC, mdavidsaver commented on src/rf_cavity.cpp
> +        //Fyc = P[0]*pow(IonEk,9)+P[1]*pow(IonEk,8)+P[2]*pow(IonEk,7)+P[3]*pow(IonEk,6)+P[4]*pow(IonEk,5)+P[5]*pow(IonEk,4)+P[6]*pow(IonEk,3)+P[7]*pow(IonEk,2)+P[8]*IonEk+P[9];
I see a lot of commented-out code being added.  Unless there is some strong reason for this, I'd suggest removing it.  If there is, then some comment explaining this would be useful in future.

I suspect the goal here is to move the magic numbers out to a file, which I like.  When this is done, it would be a good idea to make a helper function for polynomial evaluation rather than writing it out long hand each time.  Also, be aware that ```pow(double, double)``` is an expensive (and redundant) way to calculate integer powers.

2017-01-09 16:20 UTC, mdavidsaver commented on src/flame/rf_cavity.h
> +    // Harry MLP Up
In the long term, comments like this aren't so useful.  Consider removing.

2017-01-09 16:20 UTC, mdavidsaver commented on src/rf_cavity.cpp
>              lstrm >> params.type >> params.name >> params.length >> params.aperature;
As a matter of code readability, please indent blocks...

2017-01-09 16:20 UTC, mdavidsaver commented on src/rf_cavity.cpp
> +            bool needE02 = params.type!="drift" && params.type!="AccGap";
I don't see ```needE0``` ever being defined.  I assume this is a leftover from some intermediate work.  Consider reverting.

2017-01-09 16:20 UTC, mdavidsaver commented on src/rf_cavity.cpp
> +    state_t::matrix_t         Idmat, Mlon, Mtrans,Mprob,MprobLon;
Please indent consistently!

2017-01-09 16:20 UTC, mdavidsaver commented on src/rf_cavity.cpp
> +    //int seg=0;
Consider removing dead code.

2017-01-09 16:20 UTC, mdavidsaver commented on src/rf_cavity.cpp
> +            if (formatNew)
Rather than defining yet another new file format, have you considered using GLPSParser here?

2017-01-09 16:20 UTC, mdavidsaver commented on src/rf_cavity.cpp
> +	return res;
Note that ```pow(double, double)``` is an expensive way to calculate for integer powers.  It can also give a slightly different answer than simply multiplication like:

```c++
int N=8;
double *coeff = ...;
double base = ...
double P=base, result = coeff[N-1];
for(int i=N-2; i>=0; i--, P*=base)
  result += P*coeff[i];
```

Also, this function could be made a static method or free function, and could be unit-tested.

2017-01-20 16:31 UTC, kryv commented
Is there any difference between "Generic" and "Generic2" in physics part?
I believe we should add just ONE cavity type for this implementation.

Also, GLPS style cavity file can be upward compatibility of the separated style files.
I think we should remove "Generic" type and put "Generic2" as "Generic".

2017-02-13 17:27 UTC, mdavidsaver commented on src/rf_cavity.cpp
> +		tmtab = gmtime(&(attrib.st_mtime));
I think it would be simpler, safer, and more portable to use ```boost::filesystem::last_write_time()```.  This will yield the same value as ```attrib.st_mtime```.  Also, involving ```gmtime()``` seems like unnecessary complexity.

```
std::string key(SB()<<DataFile<<"|"<<boost::filesystem::last_write_time(DataFile));
```

2018-06-12 21:24 UTC, closed without merging